import type { Task } from "./app/types/tasks";

// Initial tasks for seeding the database
// These should only be used during initialization/reset
export const INITIAL_TASKS: Task[] = [
  {
    id: "water-plants",
    name: "Regar las plantas",
    description: "Regar todas las plantas de la casa y terraza",
    points: 25,
    category: "salon",
  },
  {
    id: "cook-meal",
    name: "Hacer la comida",
    description: "Preparar una comida completa",
    points: 25,
    category: "comida",
  },
  {
    id: "make-breakfast",
    name: "Hacer desayuno",
    description: "Preparar el desayuno para la casa",
    points: 25,
    category: "comida",
  },
  {
    id: "dust-and-tidy-surfaces",
    name: "Quitar el polvo y recoger superficies",
    description: "Quitar polvo y recoger las cosas de mesas y superficies",
    points: 25,
    category: "salon",
  },
  {
    id: "vacuum-floor",
    name: "Aspirar el suelo",
    description: "Aspirar el suelo de toda la casa",
    points: 25,
    category: "salon",
  },
  {
    id: "mop-floor",
    name: "Fregar el suelo",
    description: "Fregar con fregona todos los suelos de la casa",
    points: 25,
    category: "salon",
  },
  {
    id: "clean-terrace",
    name: "Hacer la terraza",
    description: "Barrer y ordenar la terraza",
    points: 25,
    category: "limpieza",
  },
  {
    id: "start-laundry",
    name: "Poner lavadora",
    description: "Clasificar y poner una lavadora",
    points: 25,
    category: "ropa",
  },
  {
    id: "bring-in-laundry",
    name: "Recoger ropa tendida",
    description: "Recoger, doblar y guardar la ropa ya seca",
    points: 25,
    category: "ropa",
  },
  {
    id: "grocery-shopping",
    name: "Hacer la compra",
    description: "Comprar comida y productos necesarios",
    points: 25,
    category: "comida",
  },
  {
    id: "clean-bathroom",
    name: "Limpiar el baño",
    description: "Limpiar inodoro, ducha, lavabo, espejo y suelo",
    points: 25,
    category: "limpieza",
  },
  {
    id: "clean-kitchen",
    name: "Limpiar la cocina",
    description: "Limpiar encimeras, fogones, fregadero y superficies",
    points: 25,
    category: "cocina",
  },
  {
    id: "wash-dishes",
    name: "Fregar los platos",
    description: "Lavar platos, vasos, cubiertos y utensilios",
    points: 25,
    category: "cocina",
  },
  {
    id: "clean-fridge",
    name: "Limpieza del frigo",
    description: "Vaciar, limpiar baldas y ordenar el frigorífico",
    points: 25,
    category: "cocina",
  },
  {
    id: "clean-oven",
    name: "Limpieza del horno",
    description: "Limpiar restos y grasa del horno",
    points: 25,
    category: "cocina",
  },
  {
    id: "change-sheets",
    name: "Cambiar las sábanas",
    description: "Quitar y poner sábanas limpias en las camas",
    points: 25,
    category: "habitacion",
  },
  {
    id: "make-bed",
    name: "Hacer la cama",
    description: "Airear y hacer la cama",
    points: 25,
    category: "habitacion",
  },
  {
    id: "take-out-trash",
    name: "Tirar la basura",
    description: "Vaciar papeleras y sacar bolsas al contenedor",
    points: 25,
    category: "cocina",
  },
  {
    id: "sweep-kitchen-floor",
    name: "Barrer suelo de cocina",
    description: "Barrer el suelo de la cocina",
    points: 25,
    category: "cocina",
  },
  {
    id: "mop-kitchen-floor",
    name: "Fregar suelo de cocina",
    description: "Fregar con fregona el suelo de la cocina",
    points: 25,
    category: "cocina",
  },
];
